#! /usr/bin/env bash

set -euo pipefail

if test -v TZ
then
  setup-timezone -z ${TZ}
fi

usermod -u $(stat -c %u /videos) opticam-dbx
if ! $(groupmod -g $(stat -c %g /videos) opticam-dbx 2>/dev/null)
then
  gpasswd -a opticam-dbx $(getent group $(stat -c %g /videos) | cut -d: -f1) >/dev/null
fi

exec sudo -E -u opticam-dbx /usr/local/bin/python -m opticam_dbx.cli $@
