#! /usr/bin/env bash

set -euo pipefail

if test -v TZ
then
  setup-timezone -z ${TZ}
fi

usermod -u $(stat -c %u /videos) opticam-dbx
groupmod -g $(stat -c %g /videos) opticam-dbx

exec sudo -E -u opticam-dbx /usr/local/bin/python -m opticam_dbx.cli $@
